### ISSUE TITLE
Controller write log

### ISSUE THREAD

**Issue by wmowm** [FantasticFiasco/serilog-sinks-http-sample-dotnet-core#76]
In the program, I can write log normally through ilogger, and in the homecontroller_ Logger cannot write to log

`            ILogger log = new LoggerConfiguration()
              .MinimumLevel.Verbose()
              .WriteTo.Http(requestUri: "http://localhost:5000/api/log")
              .WriteTo.Console()
              .ReadFrom.Configuration(configuration)
              .CreateLogger();

            log.Information("Logging xxxx");
            log.Error("Logging 999");
`

`
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            _logger.LogInformation("9999");
            _logger.LogInformation("开始记录it环境日志", DateTime.Now);

            try
            {
                _logger.LogInformation("这是it环境的业务日志");
                _logger.LogWarning("这是it环境的警告日志");
                throw new Exception();
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "这是it环境的错误日志");
            }

            return View();
        }
`

**Comment by FantasticFiasco** [comment]
Hi @wmowm.

Can you create a GitHub repository with a minimal application showcasing the issue? Thanks!

**Comment by FantasticFiasco** [comment]
Close due to inactivity.
