### ISSUE TITLE
have any plan to support https?

### ISSUE THREAD

**Issue by paulrao99** [FantasticFiasco/serilog-sinks-http-sample-dotnet-core#86]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by FantasticFiasco** [comment]
There are currently no plans to show off HTTPS in this sample application. The `Serilog.Sinks.Http` package itself has no problems sending log events over HTTPS, but I'm not sure that the purpose would be to have this specific example sending log events over HTTPS?
